### ISSUE TITLE
Couchpotato fails to start at boot

### ISSUE THREAD

**Issue by jaredbidlow** [Codehhh/ReadyNAS-Plex-Setup#1]

**Comment by Codehhh** [comment]
I don't think it's a problem with what I used. If you would like my help I
will need some form of log or at least what you're trying to do.

**Comment by jaredbidlow** [comment]
`root@ReadyNAS:~# vim  /etc/default/couchpotato
root@ReadyNAS:~# service couchpotato start
[ ok ] Starting couchpotato (via systemctl): couchpotato.service.
root@ReadyNAS:~# service couchpotato status
couchpotato.service - LSB: CouchPotato PVR for Usenet and torrents
          Loaded: loaded (/etc/init.d/couchpotato)
          Active: active (exited) since Wed, 08 Jun 2016 09:00:35 -0400; 3s ago
         Process: 5525 ExecStop=/etc/init.d/couchpotato stop (code=exited, status=2/INVALIDARGUMENT)
         Process: 6152 ExecStart=/etc/init.d/couchpotato start (code=exited, status=0/SUCCESS)
          CGroup: name=systemd:/system/couchpotato.service

Jun 08 09:00:35 ReadyNAS couchpotato[6152]: /etc/init.d/couchpotato: 1: /etc/default/couchpotato: CP_USER: not found
Jun 08 09:00:35 ReadyNAS couchpotato[6152]: /etc/init.d/couchpotato: 2: /etc/default/couchpotato: CP_HOME: not found
Jun 08 09:00:35 ReadyNAS couchpotato[6152]: /etc/init.d/couchpotato: 3: /etc/default/couchpotato: CP_DATA: not found
Jun 08 09:00:35 ReadyNAS couchpotato[6152]: /etc/init.d/couchpotato: 4: /etc/default/couchpotato: CP_PIDFILE: not found
Jun 08 09:00:35 ReadyNAS couchpotato[6152]: /etc/init.d/couchpotato: 5: /etc/default/couchpotato: PYTHON_BIN: not found
Jun 08 09:00:35 ReadyNAS couchpotato[6152]: CouchPotato: /etc/default/couchpotato unreadable, falling back to defaul...tings.
Jun 08 09:00:35 ReadyNAS couchpotato[6152]: CouchPotato: init script setup failed basic sanity checks, aborting! ... failed!
root@ReadyNAS:~#
`

**Comment by Codehhh** [comment]
Just follow the install instructions from couchpotato:

```
Install GIT with apt-get install git-core

'cd' to the folder of your choosing.

Run git clone https://github.com/CouchPotato/CouchPotatoServer.git

Then do python CouchPotatoServer/CouchPotato.py to start

To run on boot copy the init script. sudo cp CouchPotatoServer/init/ubuntu /etc/init.d/couchpotato

Change the paths inside the init script. sudo nano /etc/init.d/couchpotato

Make it executable. sudo chmod +x /etc/init.d/couchpotato

Add it to defaults. sudo update-rc.d couchpotato defaults

Open your browser and go to: http://localhost:5050/
```

**Comment by jaredbidlow** [comment]
I modified the config and it works now

```
# path to app
APP_PATH=/data/opt/CouchPotato
CP_USER=root # username to run couchpotato under (couchpotato)
CP_HOME=/data/opt/CouchPotato
CP_DATA=/data/opt/CouchPotato

# user
RUN_AS=root

# path to python bin
DAEMON=/usr/local/bin/python

# Path to store PID file
PID_FILE=/data/opt/CouchPotato/couchpotato.pid
PID_PATH=$(dirname $PID_FILE)

# script name
NAME=couchpotato

# app name
DESC=CouchPotato

# startup args
DAEMON_OPTS=" CouchPotato.py --daemon --pid_file=${PID_FILE} --data_dir=/home/user/.couchpotato"
```
`
